kind: Pod
apiVersion: v1
metadata:
    name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: course
        valueFrom:
          configMapkeyRef:
            name: nginx-config  # name of the configMap we are referring to
            key: course   # env.name and configMap key name can be different
      - name: duration
        valueFrom:
          configMapkeyRef:
            name: nginx-config
            value: duration