apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: expense
  labels:
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  # this is the pod definition
  template:
    metadata:
      # thses labels belongs to pod
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
---
# service
kind: Service
apiVersion: v1
metadata:
  name: nginx  # name of the service
spec:
  selector:
    app: nginx
    tier: frontend
  ports:       # list of the ports
  - name: nginx-svc-port
    protocol: TCP
    port: 80      # service port
    targetPort: 80     # container port(another port)